config/routes.rb
GreenVote::Application.routes.draw do
  resources :activities

  match '/landing' => 'welcome#index', :defaults => {:tagid => "6442503"}
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :votes

  resources :rooms

  resources :about
  
  resources :buildings do
    resources :votes
    collection { post :import }
  end

  root :to => 'welcome#index'
  match '*a', :to => 'welcome#index'
end

app/models/building.rb
class Building < ActiveRecord::Base
  attr_accessible :name, :address,:latitude,:longitude, :rooms_attributes,:tagId
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  has_many :rooms
  has_many :votes
  accepts_nested_attributes_for :rooms, allow_destroy: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  # POST /buildings
  # POST /buildings.json
  def index
    @buildings = Building.all
     i = 0
     @votes = []
     @buildings.each do |building|
       @votes[building.id] = Vote.where(building_id: building.id, created_at: 1.hour.ago..Time.zone.now)
      end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buildings }
    end
  end
  
  def import
    Building.import(params[:file],Building.find(params[:id]))
    redirect_to buildings_url, notice: "Rooms imported."
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @building = Building.find(params[:id])
    @votes = Vote.where(building_id: params[:id],created_at: 1.hour.ago..Time.zone.now)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @building }
    end
  end


  def new
    @building = Building.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @building }
    end
  end

  def edit
    @building = Building.find(params[:id])
  end

  def create
    @building = Building.new(params[:building])

    respond_to do |format|
      if @building.save
        format.html { redirect_to buildings_url, notice: 'building was successfully created.' }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to buildings_url, notice: 'building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

</br>
</br>
  <div>
  <h2> Rooms </h2>
  <%= f.fields_for :rooms do |builder| %>
    <%= render 'room_fields', f: builder %>
  <% end %>

  <%= link_to_add_fields "Add Room", f, :rooms %>
  </div>
<div id="test"></div>
  <div class="actions">
    <%= f.submit %>
  </div>
</br>
<div id="helpme"></div>
<% end %>

app/views/buildings/_room_fields.html.erb
<fieldset>
  <%= f.label :name, "Name:" %><br />
  <%= f.text_field :name %><br />
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/buildings/_show.html.erb
<div id="building-<%= building.id%>" class="tab-content span12 pull-left container-fluid well" style="margin-left:0px;">
	<div class="row-fluid">
		<div class="span12" style="text-align:center;">
			<h3><%= link_to building.name, building %></h3>
			<!-- <%= building.address %> -->
		</div>
	</div>
	<br>
	<div class="row-fluid">
		<div class="row-fluid">
			<div class="span8">
				<div class="row-fluid">
					<div class="span12">
						<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{building.latitude}%2C#{building.longitude}" %>
					</div>
				</div>
			</div>
			<div class="span4">
				<ul class="nav nav-list well">
					<li class="nav-header">Rooms list:</li>
					<% for room in building.rooms %>
						<li><a href="#"><%= room.name %></a></li>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<%= content_tag :div, "", id: "votes_chart"+ building.id.to_s, data: {votes: @votes[building.id], num: building.id} %>
			</div>
		</div>
	</div>
</div>
<script>
var graph = Morris.Line({
    element: 'votes_chart'+$('#votes_chart').data('num'),
    data: $('#votes_chart').data('votes'),
    xkey: 'created_at',
    ykeys: ['amount'],
    parseTime: false,
    ymin: -50.0,
    ymax: 50.0,
    hideHover: true
});

function update() {
  $.get('http://grnvote.com/buildings/' + $('#votes_chart').data('num')+ '/votes.json', function(data){
  	graph.setData(data);
  });
}

setInterval(update, 100);
</script>

app/views/buildings/edit.html.erb
<h1><%= @building.address %></h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<script>
  $('.buildingtab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
  })
</script>
  <div class="row-fluid">
    <div class="span12" style="text-align:center;">
      <h2>Building Dashboard</h2>
    </div>
  </div>
  <div class="row-fluid">
      <div class="span3 container-fluid well" style="padding:0px;">
        <ul class="nav nav-list tabbable">
          <li class="nav-header">Building List:</li>
          <% @buildings.each do |building| %>
            <li class="buildingtab"><a href="#building-<%= building.id%>"><%= building.name %></a></li>
          <% end%>
          <li class="nav-header">Building Options:</li>
          <!--<li><%= link_to 'New building', new_building_path %></li>-->
        </ul>
      </div>
      <div class="span9">
        <%= render :partial => "show", :collection => @buildings, :as => :building %>
      </div>
  </div>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>
	<div id="@building-<%= @building.id%>" class="tab-content span12 pull-left container-fluid well" style="margin-left:0px;">
		<div class="row-fluid">
			<div class="span12" style="text-align:center;">
				<h3><%= @building.name %></h3>
				<% if @building.address %>
				<%= @building.address %>
				<%end%>
			</div>
		</div>
		<br>
		<div class="row-fluid">
			<div class="row-fluid">
				<div class="span8">
					<div class="row-fluid">
						<div class="span2"></div>
						<div class="span8">
							<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@building.latitude}%2C#{@building.longitude}" %>
						</div>
						<div class="span2"></div>
					</div>
					<br>
					<div class="row-fluid">
						<div class="span12 well">
							<div class="tabbable ">
								<ul class="nav nav-tabs">
									<li class="active buildingtab"><a href="#hourly" data-toggle="tab">Hourly Data</a>
									</li>
									<li class="buildingtab"><a href="#historical" data-toggle="tab">Historical Data</a></li>
									<li class="buildingtab"><a href="#chart" data-toggle="tab">Data Chart</a></li>
								</ul>
								<div class="tabcontent">
									<div class="tab-pane active" id="hourly">
									<%= content_tag :div, "", id: "votes_chart", data: {votes: @votes, num: @building.id} %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="span4">
					<ul class="nav nav-list well">
						<li class="nav-header">Rooms list:</li>
						<% for room in @building.rooms %>
							<li><a href="#"><%= room.name %></a></li>
						<% end %>
						<li class="nav-header">Nearby locations:</li>
						<% for location in @building.nearbys(10) %>
					  		<li>
					  			<%= link_to location.name, location %>
					  		</li>
						<% end %>
						<li class="nav-header">Building menu:</li>
						<li><%= link_to 'Edit', edit_building_path(@building) %></li>
						<li><%= link_to 'Back', buildings_url %></li>
						<li><%= link_to 'Destroy', @building, method: :delete, data: { confirm: 'Are you sure?' } %></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
<div id="graph"></div>
<script>
var graph = Morris.Line({
    element: 'votes_chart',
    data: $('#votes_chart').data('votes'),
    xkey: 'created_at',
    ykeys: ['amount'],
    parseTime: false,
    ymin: -50.0,
    ymax: 50.0,
    hideHover: true
});

function update() {
  $.get('http://www.grnvote.com/buildings/' + $('#votes_chart').data('num')+ '/votes.json', function(data){
  	graph.setData(data);
  });
}
setInterval(update, 100);
</script>